version: '2'

services:
  db:
    image: mysql:5.6.26
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=foobaz
      - MYSQL_DATABASE=localdatabase
  web:
    build: .
    environment:
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_DATABASE=localdatabase
      - DB_PASSWORD=foobaz
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - ./:/app
